name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # Catch issues before they merge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout CICD-Pipeline-Project
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: List files for debugging
      run: ls -R
    - name: Build and Test
      run: mvn -B clean package --file liapp/pom.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-out
        path: target/*.jar # Saves your build result
